version: '3'
services:
  backend:
    build: .
    ports:
      - 8080:80
    depends_on:
      - database
  database:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=nome_database
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password #da cambiare sti 4
